Repository mozilla-services/syncstorage-rs, pull requests merged in 2018-11, with the labels that each got.

#77 feat: fully plugin the db into remaining handlers & server
  src/db/error.rs
  src/db/mock.rs
  src/db/mod.rs
  src/db/mysql/mod.rs
  src/db/mysql/models.rs
  src/db/mysql/pool.rs
  src/db/mysql/test.rs
  src/db/params.rs
  src/db/results.rs
  src/main.rs
  src/server/mod.rs
  src/server/test.rs
  src/web/extractors.rs
  src/web/handlers.rs
  src/web/middleware.rs
Labels: in progress

#79 feat: refactor State extraction to Box db and add put/post BSO tests
  src/web/extractors.rs
  src/web/handlers.rs
Labels: in progress

#80 fix: prefix urls w/ 1.5 and fix auth's host/port handling
  src/server/mod.rs
  src/server/test.rs
  src/web/auth.rs
Labels: bug

#81 feat(logging): enable sentry
  Cargo.lock
  Cargo.toml
  src/error.rs
  src/main.rs
Labels: in progress

#82 feat: refactor sync timestamp
  src/db/error.rs
  src/db/mysql/models.rs
  src/db/mysql/test.rs
  src/db/results.rs
  src/db/util.rs
  src/server/test.rs
  src/web/extractors.rs
Labels: in progress

#83 feat: add precondition check middleware and handler headers
  src/db/mock.rs
  src/db/mod.rs
  src/db/mysql/models.rs
  src/db/mysql/test.rs
  src/db/params.rs
  src/db/util.rs
  src/server/mod.rs
  src/web/extractors.rs
  src/web/handlers.rs
  src/web/middleware.rs
Labels: in progress

#84 fix: don't finish transactions unless one was started
  src/web/extractors.rs
  src/web/middleware.rs
Labels: in progress

#85 fix: implement batches on top of mysql
  migrations/2018-08-28-010336_init/up.sql
  src/db/error.rs
  src/db/mock.rs
  src/db/mod.rs
  src/db/mysql/batch.rs
  src/db/mysql/mod.rs
  src/db/mysql/models.rs
  src/db/mysql/schema.rs
  src/db/mysql/test.rs
  src/db/params.rs
  src/db/results.rs
  src/db/schema.rs
  src/db/schema.sql
  src/main.rs
  src/server/mod.rs
  src/web/handlers.rs
Labels: in progress

#87 feat: add get_bso_ids for full=false
  src/db/mock.rs
  src/db/mod.rs
  src/db/mysql/models.rs
  src/db/mysql/pool.rs
  src/db/mysql/test.rs
  src/db/params.rs
  src/db/results.rs
  src/db/util.rs
  src/server/test.rs
  src/web/extractors.rs
  src/web/handlers.rs
  src/web/middleware.rs
Labels: in progress

#88 feat: plugin delete_bsos to the delete_collection handler
  migrations/2018-08-28-010336_init/up.sql
  src/db/results.rs
  src/db/util.rs
  src/server/test.rs
  src/web/handlers.rs
Labels: in progress

#89 refactor: modified -> timestamp
  .travis.yml
  src/db/mock.rs
  src/db/mod.rs
  src/db/mysql/batch.rs
  src/db/mysql/models.rs
  src/db/mysql/test.rs
  src/db/params.rs
  src/db/results.rs
  src/web/handlers.rs
Labels: in progress

#91 Two tiny tweaks for Sentry
  Cargo.toml
  src/db/error.rs
  src/error.rs
Labels: in progress

#94 fix: 404 on deletes of non existent individual bsos
  README.md
  src/db/error.rs
  src/db/mod.rs
  src/db/mysql/models.rs
  src/db/mysql/pool.rs
  src/db/mysql/test.rs
  src/error.rs
  src/server/test.rs
  src/web/handlers.rs
Labels: bug, e2e tests, in progress

#95 fix: return a 415 for unsupported content-type headers
  src/error.rs
  src/server/test.rs
  src/web/error.rs
  src/web/extractors.rs
Labels: in progress

#100 feat: always set last-modified header, don't add content for 304
  src/server/mod.rs
  src/web/middleware.rs
Labels: in progress

#102 fix: return empty on get of non existent collections
  src/db/error.rs
  src/error.rs
  src/server/test.rs
  src/web/handlers.rs
Labels: bug, e2e tests, in progress

#104 feat: fix extractors, middleware for e2e tests
  src/db/mysql/batch.rs
  src/db/mysql/models.rs
  src/db/mysql/test.rs
  src/db/params.rs
  src/error.rs
  src/web/error.rs
  src/web/extractors.rs
  src/web/handlers.rs
  src/web/middleware.rs
Labels: in progress

#106 fix: use SyncTimestamp for sane WeaveTimestamp comparisons
  src/db/util.rs
  src/server/mod.rs
  src/web/middleware.rs
Labels: e2e tests, in progress

#107 feat: return newlines reply when get accept header indicates it
  src/error.rs
  src/web/error.rs
  src/web/extractors.rs
  src/web/handlers.rs
Labels: in progress
