Repository mozilla-services/syncstorage-rs, pull requests merged in 2019-10, with the labels that each got.

#208 Fix batch handling on spanner by using multiple records instead of one.
  src/db/spanner/batch.rs
  src/db/spanner/support.rs
Labels: p1

#240 fix: translate spanner's aborts into 503s
  .circleci/config.yml
  Dockerfile
  db-tests/rust-toolchain
  db-tests/src/db_tests.rs
  db-tests/src/lib.rs
  src/db/error.rs
  src/db/mod.rs
  src/db/mysql/models.rs
  src/db/mysql/pool.rs
  src/db/spanner/models.rs
  src/db/spanner/pool.rs
Labels: bug, p1

#290 fix: switch sentry to its curl transport
  Cargo.lock
  Cargo.toml
  Dockerfile
  spanner-2019-10-01.ddl
  src/main.rs
Labels: bug, p1

#256 feat: add tag support for metrics.
  db-tests/Cargo.lock
  db-tests/src/support.rs
  src/db/mod.rs
  src/db/mysql/batch.rs
  src/db/mysql/models.rs
  src/db/mysql/pool.rs
  src/db/mysql/test.rs
  src/db/spanner/batch.rs
  src/db/spanner/models.rs
  src/db/spanner/pool.rs
  src/server/metrics.rs
  src/server/mod.rs
  src/server/test.rs
Labels: 3

#303 feat: workaround timeouts w/ larger db conn sizes
  src/db/spanner/pool.rs
Labels: enhancement, p1
