Repository mozilla-services/syncstorage-rs, pull requests merged in 2019-06, with the labels that each got.

#140 feat: Add docker config
  Cargo.lock
  Cargo.toml
  Dockerfile
  docker-compose.yaml
  src/db/mysql/test.rs
  src/main.rs
  src/server/mod.rs
  src/server/test.rs
  src/settings.rs
  src/web/auth.rs
  version.json
Labels: in progress

#145 test: run unit & e2e tests on circleci
  .circleci/config.yml
  Dockerfile
  docker-compose.e2e.yaml
  docker-compose.yaml
Labels: e2e tests, enhancement, 🔄 Durable Sync

#148 refactor: cleanup clippy warnings
  .circleci/config.yml
  src/db/mysql/batch.rs
  src/db/mysql/models.rs
  src/db/mysql/test.rs
  src/db/util.rs
  src/server/test.rs
  src/web/auth.rs
  src/web/extractors.rs
  src/web/handlers.rs
Labels: cleanup, enhancement, p1

#151 fix: reject unknown fields in PUT bso
  src/server/test.rs
  src/web/extractors.rs
Labels: bug, e2e tests, 🔄 Durable Sync

#149 feat: Add debugging to track database locking failures.
  src/web/extractors.rs
  src/web/middleware.rs
Labels: bug, 🚧WIP

#154 fix: persist timestamps' decimal place precision through json
  Cargo.toml
  src/db/util.rs
  src/server/test.rs
Labels: bug, e2e tests, 🔄 Durable Sync
