Repository mozilla-services/syncstorage-rs, pull requests merged in 2019-12, with the labels that each got.

#353 fix: optimize batch commit mutations
  spanner-2019-10-01.ddl
  src/db/spanner/batch.rs
  src/db/spanner/models.rs
  src/db/spanner/support.rs
  src/web/handlers.rs
Labels: bug, cleanup, p1

#371 fix: remove duplicate header key from example script
  tools/examples/put.bash
Labels: bug

#379 chore: force cargo install to use Cargo.lock
  Dockerfile
Labels: bug

#380 fix: ignore the collection field in POSTS also
  src/server/test.rs
  src/web/extractors.rs
Labels: bug, p1
