Repository mozilla-services/syncstorage-rs, pull requests merged in 2020-04, with the labels that each got.

#577 feat: reject firefox-ios < 20 w/ a 503
  Dockerfile
  src/server/mod.rs
  src/server/test.rs
  src/web/middleware/mod.rs
  src/web/middleware/rejectua.rs
Labels: p1

#561 feat: add `--user_percent` option
  tools/user_migration/fix_collections.sql
  tools/user_migration/migrate_node.py
Labels: 2, 🚧WIP

#587 Latest ops requests for migrate_node
  tools/user_migration/README.md
  tools/user_migration/gen_bso_users.py
  tools/user_migration/gen_fxa_users.py
  tools/user_migration/migrate_node.py
Labels: 🚧WIP

#601 User migration5
  tools/user_migration/gen_bso_users.py
  tools/user_migration/gen_fxa_users.py
  tools/user_migration/migrate_node.py
Labels: 🚧WIP
